export const FETCH_MOVIES_START = 'FETCH_MOVIES_START',
  FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE',
  FETCH_BANNER_MOVIE_START = 'FETCH_BANNER_MOVIE_START',
  FETCH_BANNER_MOVIE_SUCCESS = 'FETCH_BANNER_MOVIE_SUCCESS',
  FETCH_BANNER_MOVIE_FAILURE = 'FETCH_BANNER_MOVIE_FAILURE',
  SET_TRAILER_URL = 'SET_TRAILER_URL';
